The cop InvalidCharacterLiteral has been removed
Rubocop 0.51.0 stops with this error:

Error: The `Lint/InvalidCharacterLiteral` cop has been removed since it was never being actually triggered.
(obsolete configuration found in .rubocop-https---raw-githubusercontent-com-cookpad-guides-master--rubocop-yml, please update it)